version: '3.8'
services:
  db:
    container_name: postgres_database
    restart: always
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=restuwahyu13
      - POSTGRES_PASSWORD=restuwahyu13
      - POSTGRES_DB=banks
    ports:
      - 5432:5432
    networks:
      - pg_networks
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
networks:
  pg_networks:
