version: '3.8'
services:
  web:
    container_name: express_app
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    ports:
      - 3000:3000
    networks:
      - web_network
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    container_name: pg_database
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=restuwahyu13
      - POSTGRES_PASSWORD=restuwahyu13
      - POSTGRES_DB=payment
    ports:
      - 5432:5432
    networks:
      - db_network
    volumes:
      - pgdata:/var/lib/postgresql/data
  dashboard:
    container_name: pg_admin
    restart: always
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_EMAIL_DEFAULT=restuwahyu13@zetmail.com
      - PGADMIN_PASSWORD_DEFAULT=restuwahyu13
    ports:
      - 8080:80
    networks:
      - dashboard_network
    volumes:
      - pgadmin:/var/lib/pgadmin/data
    depends_on:
      - db

volumes:
  pgdata:
  pgadmin:

networks:
  web_network:
  db_network:
  dashboard_network:
